baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a Web Designer and Front-end Developer from Denver Colorado"
disableHugoGeneratorInject = true

[[menu.main]]
  name = "About"
  url = "/#about"
  weight = 1

[[menu.main]]
  name = "Work"
  url = "/#work"
  weight = 3

#[[menu.main]]
#  name = "Notes"
#  url = "/notes"
#  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
