baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a Web Designer and Front-end Developer from Denver Colorado"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
