baseURL = "/"
languageCode = "en-us"
title = "Eric Thayer is a Web Designer and Front-end Developer from Denver Colorado"

[[menu.main]]
    name = "Work"
    url = "/#work"
    weight = 2
[[menu.main]]
   name = "About"
   url = "/#about"
   weight = 1
# [[menu.main]]
  # name = "Home"
  # url = "/"
  # weight = 0
[[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 4

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
